"""
Scanpy 分析工具
生成 Python 脚本，不直接执行
可以集成到 TaskDispatcher 中执行
"""
from typing import Dict, Any, List, Optional


class ScanpyTool:
    """
    Scanpy 分析脚本生成器
    
    核心原则：生成脚本，不直接执行数据处理
    """
    
    def __init__(self, config: Dict[str, Any] = None):
        """初始化 Scanpy 工具"""
        self.config = config or {}
        self.python_path = self.config.get("python_path", "/usr/bin/python3")
    
    def generate_workflow_script(
        self,
        input_path: str,
        output_dir: str,
        steps: List[Dict[str, Any]],
        **kwargs
    ) -> str:
        """
        生成完整的 Scanpy 工作流脚本
        
        Args:
            input_path: 输入文件路径（.h5ad 或 10x 目录）
            output_dir: 输出目录
            steps: 步骤列表，每个步骤包含 tool_id 和 params
            **kwargs: 其他参数
        
        Returns:
            Python 脚本内容
        """
        script_lines = [
            "#!/usr/bin/env python3",
            "# Scanpy Workflow Script",
            "# Generated by GIBH-Agent",
            "",
            "import scanpy as sc",
            "import pandas as pd",
            "import numpy as np",
            "import matplotlib.pyplot as plt",
            "from pathlib import Path",
            "import json",
            "",
            "# 配置",
            f"input_path = '{input_path}'",
            f"output_dir = Path('{output_dir}')",
            "output_dir.mkdir(parents=True, exist_ok=True)",
            "",
            "# 加载数据",
            "print('Loading data...')",
            "if input_path.endswith('.h5ad'):",
            "    adata = sc.read_h5ad(input_path)",
            "else:",
            "    adata = sc.read_10x_mtx(input_path, var_names='gene_symbols', cache=True)",
            "",
        ]
        
        # 生成每个步骤的代码
        for step in steps:
            tool_id = step.get("tool_id", "")
            params = step.get("params", {})
            
            step_code = self._generate_step_code(tool_id, params)
            script_lines.extend([
                f"# {step.get('name', tool_id)}",
                step_code,
                ""
            ])
        
        # 保存结果
        script_lines.extend([
            "# 保存结果",
            "output_file = output_dir / 'processed.h5ad'",
            "adata.write(output_file)",
            "print(f'Results saved to: {output_file}')",
            "",
            "# 生成报告",
            "report = {",
            "    'status': 'success',",
            "    'output_file': str(output_file),",
            "    'n_cells': adata.n_obs,",
            "    'n_genes': adata.n_vars",
            "}",
            "",
            "with open(output_dir / 'report.json', 'w') as f:",
            "    json.dump(report, f, indent=2)",
            "",
            "print('Workflow completed successfully!')"
        ])
        
        return "\\n".join(script_lines)
    
    def _generate_step_code(self, tool_id: str, params: Dict[str, Any]) -> str:
        """生成单个步骤的代码"""
        code_map = {
            "local_qc": self._qc_code(params),
            "local_normalize": self._normalize_code(),
            "local_hvg": self._hvg_code(params),
            "local_scale": self._scale_code(),
            "local_pca": self._pca_code(),
            "local_neighbors": self._neighbors_code(),
            "local_cluster": self._cluster_code(params),
            "local_umap": self._umap_code(),
            "local_tsne": self._tsne_code(),
            "local_markers": self._markers_code()
        }
        
        return code_map.get(tool_id, f"# Unknown tool: {tool_id}")
    
    def _qc_code(self, params: Dict[str, Any]) -> str:
        """QC 步骤代码"""
        min_genes = params.get("min_genes", "200")
        max_mt = params.get("max_mt", "20")
        
        return f"""# 计算 QC 指标
adata.var['mt'] = adata.var_names.str.startswith('MT-')
sc.pp.calculate_qc_metrics(adata, percent_top=None, log1p=False, inplace=True)

# 过滤
sc.pp.filter_cells(adata, min_genes={min_genes})
sc.pp.filter_genes(adata, min_cells=3)

# 过滤线粒体
adata = adata[adata.obs.pct_counts_mt < {max_mt}, :]"""
    
    def _normalize_code(self) -> str:
        """标准化步骤代码"""
        return """# 标准化
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)"""
    
    def _hvg_code(self, params: Dict[str, Any]) -> str:
        """高变基因步骤代码"""
        n_top_genes = params.get("n_top_genes", "2000")
        return f"""# 寻找高变基因
sc.pp.highly_variable_genes(adata, n_top_genes={n_top_genes}, subset=True)"""
    
    def _scale_code(self) -> str:
        """缩放步骤代码"""
        return """# 缩放
sc.pp.scale(adata, max_value=10)"""
    
    def _pca_code(self) -> str:
        """PCA 步骤代码"""
        return """# PCA
sc.tl.pca(adata, svd_solver='arpack')"""
    
    def _neighbors_code(self) -> str:
        """Neighbors 步骤代码"""
        return """# 计算邻居
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)"""
    
    def _cluster_code(self, params: Dict[str, Any]) -> str:
        """聚类步骤代码"""
        resolution = params.get("resolution", "0.5")
        return f"""# Leiden 聚类
sc.tl.leiden(adata, resolution={resolution})"""
    
    def _umap_code(self) -> str:
        """UMAP 步骤代码"""
        return """# UMAP
sc.tl.umap(adata)
sc.pl.umap(adata, color=['leiden'], save='.png')"""
    
    def _tsne_code(self) -> str:
        """t-SNE 步骤代码"""
        return """# t-SNE
sc.tl.tsne(adata)
sc.pl.tsne(adata, color=['leiden'], save='.png')"""
    
    def _markers_code(self) -> str:
        """Markers 步骤代码"""
        return """# 寻找 Marker 基因
sc.tl.rank_genes_groups(adata, 'leiden', method='wilcoxon')
markers_df = pd.DataFrame(adata.uns['rank_genes_groups']['names'])
markers_df.to_csv(output_dir / 'markers.csv')"""

